program zmienne;
const nazwa='Program "Zmienne" Agnieszki Karpiñskiej';
x=6;
y=10;
var a,b,c:real;
begin
writeln('1)');
a:=x+2;
a:=a*3;
b:=2*x;
b:=y-b;
b:=1/b;
a:=a+b;
writeln(nazwa);
writeln('Obliczenia "na raty"');
writeln(a);
writeln('Obliczenie "(x+2)*3+1/(y-2*x)"');
writeln((x+2)*3+1/(y-2*x));
writeln(' ');
writeln('2)');
a:=1+x;
a:=a*10;
b:=y*3;
a:=a/b;
writeln(nazwa);
writeln('Obliczenia "na raty"');
writeln(a);
writeln('Obliczenie "((1+x)*10)/(y*3)"');
writeln(((1+x)*10)/(y*3));
writeln(' ');
writeln('3)');
a:=7*7;
b:=x*y;
b:=b-1;
b:=3/b;
c:=6*6;
a:=a-b;
a:=a+c;
writeln(nazwa);
writeln('Obliczenia "na raty"');
writeln(a);
writeln('Obliczenie "7*7-3/(x*y-1)+6*6"');
writeln(7*7-3/(x*y-1)+6*6);
end.
