Program Dzia³ania;
const nazwa='Pierwsze samodzielne zadanie Agi';
nazwa1='Dzia³anie nr 1';
nazwa2='Dzia³anie nr 2';
nazwa3='Dzia³anie nr 3';
x=6;
y=10;
var a,b,c,d,e:real;
begin
a:=x+2;
a:=a*3;
b:=2*x;
b:=y-b;
b:=1/b;
a:=a+b;
writeln(nazwa1);
writeln('obliczenie na raty');
writeln(a);
writeln('obliczenie (x+2)*3+1/(y-2*x):');
writeln((x+2)*3+1/(y-2*x));
c:=1+x;
c:=c*10;
d:=y*3;
c:=c/d;
writeln('   ');
writeln(nazwa2);
writeln('obliczenie na raty');
writeln(c);
writeln('obliczenie ((1+x)*10)/(y*3):');
writeln(((1+x)*10)/(y*3));
e:=x*y;
e:=e-1;
e:=3/e;
e:=7*7-e+6*6;
writeln('   ');
writeln(nazwa3);
writeln('obliczenie na raty');
writeln(e);
writeln('obliczenie 7*7-3/(x*y-1)+6*6:');
writeln(7*7-3/(x*y-1)+6*6);
end.
